### ISSUE TITLE
How to fix an error with OSX paths.

### ISSUE THREAD

**Issue by elfexor** [dsheiko/nw-autoupdater#4] opened 2017-04-13 10:31 UTC
![photo_2017-04-12_17-16-32](https://cloud.githubusercontent.com/assets/20318706/25001274/5f497aa4-204d-11e7-9876-2d2aec5316c0.jpg)

The error appears after downloading and unpacking, after the application is restarted.

**Comment by dsheiko** [comment] 2017-04-15 13:10
It seems like autoupdate lib could not find the downloaded and unpacked package in tmp. That's weird. Gonna add some extra checks to make sure the update is fully ready for the swap.

**Comment by cry0m1** [comment] 2017-04-20 16:14
Possibly, try to sign macos app with your developer id (check it openes without issues), pack, unpack, sign again and pack again. Provided path `...AppTranslocation..` is a macos sandbox when something is going wrong with validity of app. Typically it  should run swap from place it was unpacked directly, path ex.: `/private/var/folders/64/sthbgckj4xgbsd_t11pfxpjc0000gn/T/` and T - means temporary.

**Comment by dsheiko** [comment] 2017-04-24 13:45
I believe the issue is fixed in 1.1.0. The backup directory was inferred wrong in a value like one above. Besides, you can set all execDir, backupDir, updateDir and logPath (to log file where everything about swap is reported). Feel free to reopen the issue, you it still persists for you

**Closed as completed by dsheiko** 2017-04-24 13:45 UTC
